-- ============================================================================
-- SecureGuide — Migration 003: Reference Data (per-list lookup tables)
-- GENERATED by scripts/build_reference_data.py — do not edit by hand.
-- One indexed bilingual lookup table per controlled list mentioned in
-- USACM v2.2.1 (§3,§4,§8) and SDT v2.2.1 (§5). Contents mirror the schema
-- CHECK constraints exactly (see scripts/validate_reference_data.py).
-- ============================================================================

PRAGMA foreign_keys = ON;

-- ARTIFACT_TYPE (USACM-3)
CREATE TABLE IF NOT EXISTS lk_artifact_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_artifact_type_sort ON lk_artifact_type(sort_order);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-REQ', 'Requirement', 'متطلب', 0);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-OBJ', 'Security Objective', 'هدف أمني', 1);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-PRI', 'Security Principle', 'مبدأ أمني', 2);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-POL', 'Security Policy', 'سياسة أمنية', 3);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-STD', 'Security Standard', 'معيار أمني', 4);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-CTR', 'Security Control', 'ضابط أمني', 5);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-CTE', 'Control Enhancement', 'تحسين ضابط', 6);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-PRO', 'Security Process', 'عملية أمنية', 7);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-PRC', 'Security Procedure', 'إجراء أمني', 8);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-PRG', 'Security Program', 'برنامج أمني', 9);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-PLN', 'Security Plan', 'خطة أمنية', 10);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-TSK', 'Task', 'مهمة', 11);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-CFG', 'Technical Configuration', 'إعداد تقني', 12);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-RUL', 'Technical Rule', 'قاعدة فنية', 13);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-EVD', 'Evidence', 'دليل', 14);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-MET', 'Metric/KPI', 'مقياس/مؤشر أداء', 15);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-EXC', 'Security Exception', 'استثناء أمني', 16);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-RSK', 'Security Risk', 'خطر أمني', 17);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-AST', 'Information Asset', 'أصل معلوماتي', 18);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-THR', 'Threat', 'تهديد', 19);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-VUL', 'Vulnerability', 'ثغرة', 20);
INSERT INTO lk_artifact_type (code, name_en, name_ar, sort_order) VALUES ('ART-OWN', 'Owner/Role', 'مالك/دور', 21);

-- ABSTRACTION_LEVEL (USACM-4.1)
CREATE TABLE IF NOT EXISTS lk_abstraction_level (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_abstraction_level_sort ON lk_abstraction_level(sort_order);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-GOV', 'Governance', 'حوكمة', 0);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-RIS', 'Risk', 'مخاطر', 1);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-POL', 'Policy', 'سياسات', 2);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-CTR', 'Control', 'ضوابط', 3);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-PRO', 'Procedure', 'إجراءات', 4);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-TEC', 'Technical', 'تقني', 5);
INSERT INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-EVM', 'Evidence/Measurement', 'أدلة/قياس', 6);

-- OBLIGATION_SOURCE (USACM-4.2)
CREATE TABLE IF NOT EXISTS lk_obligation_source (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_obligation_source_sort ON lk_obligation_source(sort_order);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-REG', 'Regulatory', 'تنظيمي', 0);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-LEG', 'Legal', 'قانوني', 1);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-CON', 'Contractual', 'تعاقدي', 2);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-STD', 'Standard', 'معياري', 3);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-INT', 'Internal', 'داخلي', 4);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-BST', 'Best Practice', 'أفضل ممارسة', 5);
INSERT INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-RSK', 'Risk-based', 'مبني على المخاطر', 6);

-- OBLIGATION_LEVEL (USACM-4.3)
CREATE TABLE IF NOT EXISTS lk_obligation_level (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_obligation_level_sort ON lk_obligation_level(sort_order);
INSERT INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-MND', 'Mandatory', 'إلزامي', 0);
INSERT INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-CON', 'Conditional', 'مشروط', 1);
INSERT INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-REC', 'Recommended', 'موصى به', 2);
INSERT INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-OPT', 'Optional', 'اختياري', 3);

-- EXCEPTION_STATUS (USACM-4.4)
CREATE TABLE IF NOT EXISTS lk_exception_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_exception_status_sort ON lk_exception_status(sort_order);
INSERT INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-NONE', 'None', 'لا يوجد', 0);
INSERT INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-NOT-APPLICABLE', 'Not Applicable', 'غير منطبق', 1);
INSERT INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-RISK-ACCEPTED', 'Risk Accepted', 'مقبول مع المخاطرة', 2);
INSERT INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-DEFERRED', 'Deferred', 'مؤجل', 3);
INSERT INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-UNAVAILABLE', 'Unavailable', 'غير متاح', 4);

-- GRANULARITY_LEVEL (USACM-4.5)
CREATE TABLE IF NOT EXISTS lk_granularity_level (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_granularity_level_sort ON lk_granularity_level(sort_order);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-HIGH', 'High-level', NULL, 0);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-MEDIUM', 'Medium', NULL, 1);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-DETAILED', 'Detailed', NULL, 2);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-EXECUTABLE', 'Executable', NULL, 3);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-TECHNICAL', 'Technical', NULL, 4);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-EVIDENTIARY', 'Evidentiary', NULL, 5);
INSERT INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-METRIC', 'Metric', NULL, 6);

-- CONTROL_NATURE (USACM-4.6)
CREATE TABLE IF NOT EXISTS lk_control_nature (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_control_nature_sort ON lk_control_nature(sort_order);
INSERT INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-ORG', 'Organizational', 'تنظيمي', 0);
INSERT INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-HUM', 'Human', 'بشري', 1);
INSERT INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-PHY', 'Physical', 'مادي', 2);
INSERT INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-TEC', 'Technical', 'تقني', 3);

-- CONTROL_FUNCTION (USACM-4.7)
CREATE TABLE IF NOT EXISTS lk_control_function (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_control_function_sort ON lk_control_function(sort_order);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-PRE', 'Preventive', 'وقائي', 0);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-DET', 'Detective', 'كشفي', 1);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-COR', 'Corrective', 'تصحيحي', 2);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-REC', 'Recovery', 'استرداد', 3);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-DRR', 'Deterrent', 'ردعي', 4);
INSERT INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-COM', 'Compensating', 'تعويضي', 5);

-- TESTABILITY (USACM-4.8)
CREATE TABLE IF NOT EXISTS lk_testability (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_testability_sort ON lk_testability(sort_order);
INSERT INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-AUTO', 'Automated', 'آلي', 0);
INSERT INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-MAN', 'Manual', 'يدوي', 1);
INSERT INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-DOC', 'Documentary', 'مستندي', 2);
INSERT INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-INT', 'Interview', 'مقابلة', 3);
INSERT INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-NA', 'Not Testable', 'غير قابل للفحص', 4);

-- IMPLEMENTATION_STATUS (USACM-4.9)
CREATE TABLE IF NOT EXISTS lk_implementation_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_implementation_status_sort ON lk_implementation_status(sort_order);
INSERT INTO lk_implementation_status (code, name_en, name_ar, sort_order) VALUES ('STS-NOT-APPLIED', 'Not Applied', 'غير مطبّق', 0);
INSERT INTO lk_implementation_status (code, name_en, name_ar, sort_order) VALUES ('STS-PARTIAL', 'Partial', 'مطبّق جزئياً', 1);
INSERT INTO lk_implementation_status (code, name_en, name_ar, sort_order) VALUES ('STS-FULL', 'Full', 'مطبّق كلياً', 2);
INSERT INTO lk_implementation_status (code, name_en, name_ar, sort_order) VALUES ('STS-PLANNED', 'Planned', 'مخطّط له', 3);
INSERT INTO lk_implementation_status (code, name_en, name_ar, sort_order) VALUES ('STS-NEEDS-IMPROVEMENT', 'Needs Improvement', 'يحتاج تحسيناً', 4);

-- VERIFICATION_STATUS (USACM-4.10)
CREATE TABLE IF NOT EXISTS lk_verification_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_verification_status_sort ON lk_verification_status(sort_order);
INSERT INTO lk_verification_status (code, name_en, name_ar, sort_order) VALUES ('VER-NOT-VERIFIED', 'Not Verified', 'لم يُتحقق', 0);
INSERT INTO lk_verification_status (code, name_en, name_ar, sort_order) VALUES ('VER-PASS', 'Pass', 'نجح', 1);
INSERT INTO lk_verification_status (code, name_en, name_ar, sort_order) VALUES ('VER-FAIL', 'Fail', 'فشل', 2);

-- EFFECTIVENESS (USACM-4.11)
CREATE TABLE IF NOT EXISTS lk_effectiveness (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_effectiveness_sort ON lk_effectiveness(sort_order);
INSERT INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-LOW', 'Low', 'ضعيفة', 0);
INSERT INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-MEDIUM', 'Medium', 'متوسطة', 1);
INSERT INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-HIGH', 'High', 'عالية', 2);
INSERT INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-UNKNOWN', 'Unknown', 'غير معروفة', 3);

-- PRIORITY (USACM-4.12)
CREATE TABLE IF NOT EXISTS lk_priority (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_priority_sort ON lk_priority(sort_order);
INSERT INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-CRITICAL', 'Critical', 'حرجة', 0);
INSERT INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-HIGH', 'High', 'عالية', 1);
INSERT INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-MEDIUM', 'Medium', 'متوسطة', 2);
INSERT INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-LOW', 'Low', 'منخفضة', 3);

-- RELATIONSHIP_TYPE (USACM-4.13)
CREATE TABLE IF NOT EXISTS lk_relationship_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_relationship_type_sort ON lk_relationship_type(sort_order);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-DER', 'Derives From', 'مشتق من', 0);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-SAT', 'Satisfies', 'يحقق', 1);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-SUP', 'Supports', 'يدعم', 2);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-SPL', 'Specifies', 'يحدد', 3);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-IMP', 'Implements', 'يطبّق', 4);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-VER', 'Verifies', 'يتحقق من', 5);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-MEA', 'Measures', 'يقيس', 6);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-MIT', 'Mitigates', 'يخفف', 7);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-AFF', 'Affects', 'يؤثر على', 8);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-EXC', 'Exempts', 'يعفي', 9);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-DEP', 'Depends On', 'يعتمد على', 10);
INSERT INTO lk_relationship_type (code, name_en, name_ar, sort_order) VALUES ('REL-CNF', 'Conflicts With', 'يتعارض مع', 11);

-- AI_REVIEW_STATUS (USACM-4.14)
CREATE TABLE IF NOT EXISTS lk_ai_review_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_ai_review_status_sort ON lk_ai_review_status(sort_order);
INSERT INTO lk_ai_review_status (code, name_en, name_ar, sort_order) VALUES ('AIR-AUTO-ACCEPTED', 'Auto Accepted', 'مقبول آلياً', 0);
INSERT INTO lk_ai_review_status (code, name_en, name_ar, sort_order) VALUES ('AIR-HUMAN-REVIEW', 'Human Review', 'مراجعة بشرية', 1);
INSERT INTO lk_ai_review_status (code, name_en, name_ar, sort_order) VALUES ('AIR-HUMAN-APPROVED', 'Human Approved', 'معتمد بشرياً', 2);
INSERT INTO lk_ai_review_status (code, name_en, name_ar, sort_order) VALUES ('AIR-HUMAN-REJECTED', 'Human Rejected', 'مرفوض بشرياً', 3);

-- REQUIREMENT_TYPE (USACM-4.15)
CREATE TABLE IF NOT EXISTS lk_requirement_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_requirement_type_sort ON lk_requirement_type(sort_order);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-GOV', 'Governance', 'حوكمة', 0);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-REG', 'Regulatory', 'تنظيمي', 1);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-LEG', 'Legal', 'قانوني', 2);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-CON', 'Contractual', 'تعاقدي', 3);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-STD', 'Standard', 'معياري', 4);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-INT', 'Internal', 'داخلي', 5);
INSERT INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-RSK', 'Risk-based', 'مبني على المخاطر', 6);

-- MAPPING_STRENGTH (USACM-4.16)
CREATE TABLE IF NOT EXISTS lk_mapping_strength (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_mapping_strength_sort ON lk_mapping_strength(sort_order);
INSERT INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('DIRECT', 'Direct', 'مباشر', 0);
INSERT INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('INDIRECT', 'Indirect', 'غير مباشر', 1);
INSERT INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('PARTIAL', 'Partial', 'جزئي', 2);
INSERT INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('INFORMATIVE', 'Informative', 'إرشادي', 3);

-- TAG_TYPE (USACM-4.17)
CREATE TABLE IF NOT EXISTS lk_tag_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_tag_type_sort ON lk_tag_type(sort_order);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Technology', 'Technology', 'تقنية', 0);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Framework', 'Framework', 'إطار', 1);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Concept', 'Concept', 'مفهوم', 2);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Context', 'Context', 'سياق', 3);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Threat', 'Threat', 'تهديد', 4);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Data', 'Data', 'بيانات', 5);
INSERT INTO lk_tag_type (code, name_en, name_ar, sort_order) VALUES ('Party', 'Party', 'طرف', 6);

-- REVIEW_FREQUENCY (USACM-4.18)
CREATE TABLE IF NOT EXISTS lk_review_frequency (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_review_frequency_sort ON lk_review_frequency(sort_order);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('DAILY', 'Daily', 'يومي', 0);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('WEEKLY', 'Weekly', 'أسبوعي', 1);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('MONTHLY', 'Monthly', 'شهري', 2);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('QUARTERLY', 'Quarterly', 'ربع سنوي', 3);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('SEMI-ANNUAL', 'Semi-Annual', 'نصف سنوي', 4);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('ANNUAL', 'Annual', 'سنوي', 5);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('BIENNIAL', 'Biennial', 'كل سنتين', 6);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('AD-HOC', 'Ad-hoc', 'عند الحاجة', 7);
INSERT INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('CONTINUOUS', 'Continuous', 'مستمر', 8);

-- PUBLICATION_STATUS (USACM-4.19)
CREATE TABLE IF NOT EXISTS lk_publication_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_publication_status_sort ON lk_publication_status(sort_order);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('DRAFT', 'Draft', 'مسودة', 0);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('UNDER_REVIEW', 'Under Review', 'قيد المراجعة', 1);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('APPROVED', 'Approved', 'معتمد', 2);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('PUBLISHED', 'Published', 'منشور', 3);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('DEPRECATED', 'Deprecated', 'مهمَل', 4);
INSERT INTO lk_publication_status (code, name_en, name_ar, sort_order) VALUES ('WITHDRAWN', 'Withdrawn', 'مسحوب', 5);

-- SOURCE_TYPE (USACM-4.20)
CREATE TABLE IF NOT EXISTS lk_source_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_source_type_sort ON lk_source_type(sort_order);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('DOCUMENT', 'Document', 'مستند', 0);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('SYSTEM', 'System', 'نظام', 1);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('TOOL', 'Tool', 'أداة', 2);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('INTERVIEW', 'Interview', 'مقابلة', 3);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('OBSERVATION', 'Observation', 'ملاحظة', 4);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('STANDARD', 'Standard', 'معيار', 5);
INSERT INTO lk_source_type (code, name_en, name_ar, sort_order) VALUES ('REGULATION', 'Regulation', 'لائحة', 6);

-- CATALOG_SOURCE_TYPE (SCHEMA-001)
CREATE TABLE IF NOT EXISTS lk_catalog_source_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_catalog_source_type_sort ON lk_catalog_source_type(sort_order);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('FRAMEWORK', 'Framework', 'إطار', 0);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('STANDARD', 'Standard', 'معيار', 1);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('THREAT_INTEL', 'Threat Intelligence', 'استخبارات تهديد', 2);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('GUIDELINE', 'Guideline', 'إرشادات', 3);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('POLICY_TEMPLATE', 'Policy Template', 'قالب سياسة', 4);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('REGULATION', 'Regulation', 'لائحة', 5);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('DOCUMENT', 'Document', 'مستند', 6);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('SYSTEM', 'System', 'نظام', 7);
INSERT INTO lk_catalog_source_type (code, name_en, name_ar, sort_order) VALUES ('TOOL', 'Tool', 'أداة', 8);

-- ASSET_TYPE (USACM-4.21)
CREATE TABLE IF NOT EXISTS lk_asset_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_asset_type_sort ON lk_asset_type(sort_order);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('HARDWARE', 'Hardware', 'أجهزة', 0);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('SOFTWARE', 'Software', 'برمجيات', 1);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('DATA', 'Data', 'بيانات', 2);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('SERVICE', 'Service', 'خدمة', 3);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('FACILITY', 'Facility', 'منشأة', 4);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('PERSONNEL', 'Personnel', 'أفراد', 5);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('NETWORK', 'Network', 'شبكة', 6);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('CLOUD_INSTANCE', 'Cloud Instance', 'نسخة سحابية', 7);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('DOCUMENT', 'Document', 'وثيقة', 8);
INSERT INTO lk_asset_type (code, name_en, name_ar, sort_order) VALUES ('INTELLECTUAL_PROPERTY', 'Intellectual Property', 'ملكية فكرية', 9);

-- MATURITY_LEVEL (USACM-4.22)
CREATE TABLE IF NOT EXISTS lk_maturity_level (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_maturity_level_sort ON lk_maturity_level(sort_order);
INSERT INTO lk_maturity_level (code, name_en, name_ar, sort_order) VALUES ('INITIAL', 'Initial', 'مبدئي', 0);
INSERT INTO lk_maturity_level (code, name_en, name_ar, sort_order) VALUES ('REPEATABLE', 'Repeatable', 'قابل للتكرار', 1);
INSERT INTO lk_maturity_level (code, name_en, name_ar, sort_order) VALUES ('DEFINED', 'Defined', 'محدد', 2);
INSERT INTO lk_maturity_level (code, name_en, name_ar, sort_order) VALUES ('MANAGED', 'Managed', 'مُدار', 3);
INSERT INTO lk_maturity_level (code, name_en, name_ar, sort_order) VALUES ('OPTIMIZED', 'Optimized', 'مُحسَّن', 4);

-- COST_CATEGORY (USACM-4.23)
CREATE TABLE IF NOT EXISTS lk_cost_category (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_cost_category_sort ON lk_cost_category(sort_order);
INSERT INTO lk_cost_category (code, name_en, name_ar, sort_order) VALUES ('LOW', 'Low', 'منخفضة', 0);
INSERT INTO lk_cost_category (code, name_en, name_ar, sort_order) VALUES ('MEDIUM', 'Medium', 'متوسطة', 1);
INSERT INTO lk_cost_category (code, name_en, name_ar, sort_order) VALUES ('HIGH', 'High', 'عالية', 2);
INSERT INTO lk_cost_category (code, name_en, name_ar, sort_order) VALUES ('VERY_HIGH', 'Very High', 'عالية جداً', 3);

-- IMPORT_STATUS (USACM-4.24)
CREATE TABLE IF NOT EXISTS lk_import_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_import_status_sort ON lk_import_status(sort_order);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('NEW', 'New', 'جديد', 0);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('IMPORTED', 'Imported', 'مستورد', 1);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('UPDATED', 'Updated', 'محدّث', 2);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('MERGED', 'Merged', 'مدموج', 3);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('CONFLICT', 'Conflict', 'متعارض', 4);
INSERT INTO lk_import_status (code, name_en, name_ar, sort_order) VALUES ('REJECTED', 'Rejected', 'مرفوض', 5);

-- APPLICABILITY_SCOPE_TYPE (USACM-8)
CREATE TABLE IF NOT EXISTS lk_applicability_scope_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_applicability_scope_type_sort ON lk_applicability_scope_type(sort_order);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('ORGANIZATION_SIZE', 'Organization Size', 'حجم المؤسسة', 0);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('INDUSTRY', 'Industry', 'القطاع', 1);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('GEOGRAPHIC_REGION', 'Geographic Region', 'المنطقة الجغرافية', 2);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('BUSINESS_UNIT', 'Business Unit', 'وحدة العمل', 3);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('ENTITY_TYPE', 'Entity Type', 'نوع الكيان', 4);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('REGULATORY_SCOPE', 'Regulatory Scope', 'النطاق التنظيمي', 5);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('REGULATORY_JURISDICTION', 'Regulatory Jurisdiction', 'الاختصاص التنظيمي', 6);
INSERT INTO lk_applicability_scope_type (code, name_en, name_ar, sort_order) VALUES ('EXCLUSION', 'Exclusion', 'استثناء', 7);

-- DEPENDENCY_TYPE (USACM-8)
CREATE TABLE IF NOT EXISTS lk_dependency_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_dependency_type_sort ON lk_dependency_type(sort_order);
INSERT INTO lk_dependency_type (code, name_en, name_ar, sort_order) VALUES ('SYSTEM', 'System', NULL, 0);
INSERT INTO lk_dependency_type (code, name_en, name_ar, sort_order) VALUES ('PLATFORM', 'Platform', NULL, 1);
INSERT INTO lk_dependency_type (code, name_en, name_ar, sort_order) VALUES ('VENDOR', 'Vendor', NULL, 2);
INSERT INTO lk_dependency_type (code, name_en, name_ar, sort_order) VALUES ('SKILL', 'Skill', NULL, 3);
INSERT INTO lk_dependency_type (code, name_en, name_ar, sort_order) VALUES ('BUDGET', 'Budget', NULL, 4);

-- DEPENDENCY_STATUS (USACM-8)
CREATE TABLE IF NOT EXISTS lk_dependency_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_dependency_status_sort ON lk_dependency_status(sort_order);
INSERT INTO lk_dependency_status (code, name_en, name_ar, sort_order) VALUES ('AVAILABLE', 'Available', NULL, 0);
INSERT INTO lk_dependency_status (code, name_en, name_ar, sort_order) VALUES ('NOT_AVAILABLE', 'Not Available', NULL, 1);
INSERT INTO lk_dependency_status (code, name_en, name_ar, sort_order) VALUES ('PARTIAL', 'Partial', NULL, 2);
INSERT INTO lk_dependency_status (code, name_en, name_ar, sort_order) VALUES ('PLANNED', 'Planned', NULL, 3);

-- VERIFICATION_TOOL_TYPE (USACM-8)
CREATE TABLE IF NOT EXISTS lk_verification_tool_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_verification_tool_type_sort ON lk_verification_tool_type(sort_order);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('SIEM', 'SIEM', NULL, 0);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('EDR', 'EDR', NULL, 1);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('IAM', 'IAM', NULL, 2);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('VULNERABILITY', 'Vulnerability', NULL, 3);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('CSPM', 'CSPM', NULL, 4);
INSERT INTO lk_verification_tool_type (code, name_en, name_ar, sort_order) VALUES ('MANUAL', 'Manual', NULL, 5);

-- VERIFICATION_METHOD (USACM-8)
CREATE TABLE IF NOT EXISTS lk_verification_method (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_verification_method_sort ON lk_verification_method(sort_order);
INSERT INTO lk_verification_method (code, name_en, name_ar, sort_order) VALUES ('API', 'API', NULL, 0);
INSERT INTO lk_verification_method (code, name_en, name_ar, sort_order) VALUES ('LOG', 'Log', NULL, 1);
INSERT INTO lk_verification_method (code, name_en, name_ar, sort_order) VALUES ('REPORT', 'Report', NULL, 2);
INSERT INTO lk_verification_method (code, name_en, name_ar, sort_order) VALUES ('INTERVIEW', 'Interview', NULL, 3);
INSERT INTO lk_verification_method (code, name_en, name_ar, sort_order) VALUES ('OBSERVATION', 'Observation', NULL, 4);

-- STAKEHOLDER_RESPONSIBILITY (USACM-8)
CREATE TABLE IF NOT EXISTS lk_stakeholder_responsibility (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_stakeholder_responsibility_sort ON lk_stakeholder_responsibility(sort_order);
INSERT INTO lk_stakeholder_responsibility (code, name_en, name_ar, sort_order) VALUES ('OWNER', 'Owner', 'مالك', 0);
INSERT INTO lk_stakeholder_responsibility (code, name_en, name_ar, sort_order) VALUES ('REVIEWER', 'Reviewer', 'مراجع', 1);
INSERT INTO lk_stakeholder_responsibility (code, name_en, name_ar, sort_order) VALUES ('APPROVER', 'Approver', 'معتمِد', 2);
INSERT INTO lk_stakeholder_responsibility (code, name_en, name_ar, sort_order) VALUES ('CONSULTED', 'Consulted', 'مستشار', 3);
INSERT INTO lk_stakeholder_responsibility (code, name_en, name_ar, sort_order) VALUES ('INFORMED', 'Informed', 'مُبلَّغ', 4);

-- EXTERNAL_REFERENCE_TYPE (USACM-8)
CREATE TABLE IF NOT EXISTS lk_external_reference_type (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_external_reference_type_sort ON lk_external_reference_type(sort_order);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('ARTICLE', 'Article', NULL, 0);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('BLOG', 'Blog', NULL, 1);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('TOOL', 'Tool', NULL, 2);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('VIDEO', 'Video', NULL, 3);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('STUDY', 'Study', NULL, 4);
INSERT INTO lk_external_reference_type (code, name_en, name_ar, sort_order) VALUES ('BENCHMARK', 'Benchmark', NULL, 5);

-- SELF_ASSESSMENT_STATUS (USACM-8)
CREATE TABLE IF NOT EXISTS lk_self_assessment_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_self_assessment_status_sort ON lk_self_assessment_status(sort_order);
INSERT INTO lk_self_assessment_status (code, name_en, name_ar, sort_order) VALUES ('NOT_ASSESSED', 'Not Assessed', NULL, 0);
INSERT INTO lk_self_assessment_status (code, name_en, name_ar, sort_order) VALUES ('IN_PROGRESS', 'In Progress', NULL, 1);
INSERT INTO lk_self_assessment_status (code, name_en, name_ar, sort_order) VALUES ('COMPLETED', 'Completed', NULL, 2);
INSERT INTO lk_self_assessment_status (code, name_en, name_ar, sort_order) VALUES ('NEEDS_REVIEW', 'Needs Review', NULL, 3);

-- RESOLUTION_STATUS (USACM-8)
CREATE TABLE IF NOT EXISTS lk_resolution_status (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_resolution_status_sort ON lk_resolution_status(sort_order);
INSERT INTO lk_resolution_status (code, name_en, name_ar, sort_order) VALUES ('PENDING', 'Pending', NULL, 0);
INSERT INTO lk_resolution_status (code, name_en, name_ar, sort_order) VALUES ('RESOLVED', 'Resolved', NULL, 1);
INSERT INTO lk_resolution_status (code, name_en, name_ar, sort_order) VALUES ('ACCEPTED', 'Accepted', NULL, 2);
INSERT INTO lk_resolution_status (code, name_en, name_ar, sort_order) VALUES ('REJECTED', 'Rejected', NULL, 3);

-- SDT_DOMAIN (SDT-5)
CREATE TABLE IF NOT EXISTS lk_sdt_domain (
    code       TEXT PRIMARY KEY,
    name_en    TEXT,
    name_ar    TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lk_sdt_domain_sort ON lk_sdt_domain(sort_order);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-01', 'Governance, Risk & Compliance', 'الحوكمة والمخاطر والامتثال', 0);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-02', 'Assets, Data & Privacy', 'الأصول والبيانات والخصوصية', 1);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-03', 'Identity, Access & Privilege', 'الهوية والوصول والامتياز', 2);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-04', 'Infrastructure, Network & Cloud', 'البنية التحتية والشبكة والسحابة', 3);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-05', 'Applications, Development & Change', 'التطبيقات والتطوير والتغيير', 4);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-06', 'Detection, Monitoring & Vulnerability', 'الكشف والمراقبة والثغرات', 5);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-07', 'Response, Recovery & Resilience', 'الاستجابة والتعافي والصمود', 6);
INSERT INTO lk_sdt_domain (code, name_en, name_ar, sort_order) VALUES ('SD-08', 'People, Third Parties & Physical', 'الأشخاص والأطراف الثالثة والأمن المادي', 7);

-- SDT_SUBDOMAIN (SDT-5.1) — FK domain_code -> lk_sdt_domain(code)
CREATE TABLE IF NOT EXISTS lk_sdt_subdomain (
    code        TEXT PRIMARY KEY,
    name_en     TEXT,
    name_ar     TEXT,
    domain_code TEXT NOT NULL REFERENCES lk_sdt_domain(code),
    sort_order  INTEGER NOT NULL DEFAULT 0,
    CHECK (substr(code,1,5) = domain_code)
);
CREATE INDEX IF NOT EXISTS idx_lk_sdt_subdomain_domain ON lk_sdt_subdomain(domain_code, sort_order);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-01.01', 'Cybersecurity Strategy & Governance', 'استراتيجية وحوكمة الأمن السيبراني', 'SD-01', 0);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-01.02', 'Policies, Standards & Exceptions', 'السياسات والمعايير والاستثناءات', 'SD-01', 1);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-01.03', 'Security Risk Management', 'إدارة المخاطر الأمنية', 'SD-01', 2);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-01.04', 'Compliance, Audit & Assurance', 'الامتثال والتدقيق والضمان', 'SD-01', 3);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-01.05', 'Security Program Management & Metrics', 'إدارة البرنامج الأمني والمقاييس', 'SD-01', 4);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-02.01', 'Asset Inventory & Management', 'جرد وإدارة الأصول', 'SD-02', 5);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-02.02', 'Software & License Management', 'إدارة البرمجيات والتراخيص', 'SD-02', 6);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-02.03', 'Data Classification & Ownership', 'تصنيف وملكية البيانات', 'SD-02', 7);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-02.04', 'Data Protection & Encryption', 'حماية البيانات والتشفير', 'SD-02', 8);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-02.05', 'Privacy, Retention & Disposal', 'الخصوصية والاحتفاظ والإتلاف', 'SD-02', 9);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-03.01', 'Identity Lifecycle Management', 'إدارة دورة حياة الهوية', 'SD-03', 10);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-03.02', 'Authentication & Credential Management', 'المصادقة وإدارة بيانات الاعتماد', 'SD-03', 11);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-03.03', 'Authorization & Access Management', 'التخويل وإدارة الوصول', 'SD-03', 12);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-03.04', 'Privileged Access Management', 'إدارة الوصول المتميز', 'SD-03', 13);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-03.05', 'Remote & External Access', 'الوصول عن بُعد والخارجي', 'SD-03', 14);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-04.01', 'Network & Communications Security', 'أمن الشبكات والاتصالات', 'SD-04', 15);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-04.02', 'Systems, Servers & Endpoint Security', 'أمن الأنظمة والخوادم والأجهزة الطرفية', 'SD-04', 16);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-04.03', 'Configuration & Security Hardening', 'الإعداد والتحصين الأمني', 'SD-04', 17);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-04.04', 'Cloud & Virtual Platform Security', 'أمن المنصات السحابية والافتراضية', 'SD-04', 18);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-04.05', 'Email, Web & Digital Communications', 'البريد والويب والاتصالات الرقمية', 'SD-04', 19);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-05.01', 'Application Security Governance & SDLC', 'حوكمة أمن التطبيقات ودورة حياة التطوير', 'SD-05', 20);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-05.02', 'Application & API Security Testing', 'اختبار أمن التطبيقات وواجهات API', 'SD-05', 21);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-05.03', 'Code, Components & Software Supply Chain', 'الشيفرة والمكونات وسلسلة توريد البرمجيات', 'SD-05', 22);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-05.04', 'Change & Release Management', 'إدارة التغيير والإصدار', 'SD-05', 23);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-05.05', 'Database & Critical Application Security', 'أمن قواعد البيانات والتطبيقات الحرجة', 'SD-05', 24);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-06.01', 'Logging & Security Monitoring', 'التسجيل والمراقبة الأمنية', 'SD-06', 25);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-06.02', 'Threat Detection & Alerts', 'كشف التهديدات والتنبيهات', 'SD-06', 26);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-06.03', 'Vulnerability & Patch Management', 'إدارة الثغرات والتحديثات', 'SD-06', 27);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-06.04', 'Security Testing & Assessments', 'الاختبار والتقييم الأمني', 'SD-06', 28);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-06.05', 'Threat Intelligence & IoCs', 'استخبارات التهديدات ومؤشرات الاختراق', 'SD-06', 29);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-07.01', 'Incident Management', 'إدارة الحوادث', 'SD-07', 30);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-07.02', 'Digital Forensics & Evidence', 'التحليل الجنائي الرقمي والأدلة', 'SD-07', 31);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-07.03', 'Backup & Restore', 'النسخ الاحتياطي والاستعادة', 'SD-07', 32);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-07.04', 'Business Continuity & Disaster Recovery', 'استمرارية الأعمال والتعافي من الكوارث', 'SD-07', 33);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-07.05', 'Crisis Management & Communication', 'إدارة الأزمات والتواصل', 'SD-07', 34);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-08.01', 'Awareness, Training & Security Culture', 'التوعية والتدريب وثقافة الأمن', 'SD-08', 35);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-08.02', 'HR Security & Employee Lifecycle', 'أمن الموارد البشرية ودورة حياة الموظف', 'SD-08', 36);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-08.03', 'Supplier & Third-Party Management', 'إدارة الموردين والأطراف الثالثة', 'SD-08', 37);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-08.04', 'Physical & Environmental Security', 'الأمن المادي والبيئي', 'SD-08', 38);
INSERT INTO lk_sdt_subdomain (code, name_en, name_ar, domain_code, sort_order) VALUES ('SD-08.05', 'Acceptable Use & Professional Conduct', 'الاستخدام المقبول والسلوك المهني', 'SD-08', 39);
