-- ============================================================================
-- SecureGuide — Migration 009: Reference Extensions (content-enrichment layer)
-- GENERATED by scripts/build_reference_ext.py — do not edit by hand.
-- New lk_* extension lists (with usacm_map) + scoring policy/bands + amani alias.
-- Kept separate from 003 so migrations 001-006 are never modified.
-- ============================================================================

PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO schema_migrations (version, description) VALUES ('009','Reference extensions: enrichment lk_* + scoring policy/bands + amani domain alias');

-- lk_security_objective
CREATE TABLE IF NOT EXISTS lk_security_objective (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('confidentiality','Confidentiality','السرية',NULL,'CIA property; no USACM canonical',0);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('integrity','Integrity','السلامة',NULL,NULL,1);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('availability','Availability','التوافر',NULL,NULL,2);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('authenticity','Authenticity','الأصالة',NULL,NULL,3);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('accountability','Accountability','المساءلة',NULL,NULL,4);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('non_repudiation','Non-Repudiation','عدم الإنكار',NULL,NULL,5);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('privacy','Privacy','الخصوصية',NULL,'hint SD-02',6);
INSERT OR IGNORE INTO lk_security_objective (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('safety','Safety','السلامة العامة',NULL,NULL,7);

-- lk_objective_strength
CREATE TABLE IF NOT EXISTS lk_objective_strength (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_objective_strength (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('primary','Primary','أساسي',NULL,NULL,0);
INSERT OR IGNORE INTO lk_objective_strength (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('supporting','Supporting','داعم',NULL,NULL,1);
INSERT OR IGNORE INTO lk_objective_strength (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('none','None','لا يوجد',NULL,NULL,2);

-- lk_csf_function
CREATE TABLE IF NOT EXISTS lk_csf_function (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('govern','Govern','الحوكمة','ABS-GOV',NULL,0);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('identify','Identify','التعريف','ABS-RIS',NULL,1);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('protect','Protect','الحماية','FUN-PRE',NULL,2);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('detect','Detect','الكشف','FUN-DET',NULL,3);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('respond','Respond','الاستجابة','FUN-COR',NULL,4);
INSERT OR IGNORE INTO lk_csf_function (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('recover','Recover','التعافي','FUN-REC',NULL,5);

-- lk_control_purpose
CREATE TABLE IF NOT EXISTS lk_control_purpose (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('preventive','Preventive','وقائي','FUN-PRE',NULL,0);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('deterrent','Deterrent','ردعي','FUN-DRR',NULL,1);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('detective','Detective','كشفي','FUN-DET',NULL,2);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('corrective','Corrective','تصحيحي','FUN-COR',NULL,3);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('containment','Containment','احتواء','FUN-COR',NULL,4);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('recovery','Recovery','استرداد','FUN-REC',NULL,5);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('compensating','Compensating','تعويضي','FUN-COM',NULL,6);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('directive','Directive','توجيهي','FUN-PRE',NULL,7);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('monitoring','Monitoring','مراقبة','FUN-DET',NULL,8);
INSERT OR IGNORE INTO lk_control_purpose (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('assurance','Assurance','ضمان','FUN-DET',NULL,9);

-- lk_implementation_type
CREATE TABLE IF NOT EXISTS lk_implementation_type (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('administrative','Administrative','إداري','NAT-ORG',NULL,0);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('technical','Technical','تقني','NAT-TEC',NULL,1);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('operational','Operational','تشغيلي','NAT-ORG',NULL,2);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('physical','Physical','مادي','NAT-PHY',NULL,3);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('human','Human','بشري','NAT-HUM',NULL,4);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('legal_contractual','Legal/Contractual','قانوني/تعاقدي','NAT-ORG',NULL,5);
INSERT OR IGNORE INTO lk_implementation_type (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('architectural','Architectural','معماري','NAT-TEC',NULL,6);

-- lk_tier
CREATE TABLE IF NOT EXISTS lk_tier (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_tier (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('essential','Essential','أساسي','INITIAL',NULL,0);
INSERT OR IGNORE INTO lk_tier (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('advanced','Advanced','متقدّم','DEFINED',NULL,1);
INSERT OR IGNORE INTO lk_tier (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('very_advanced','Very Advanced','متقدّم جداً','MANAGED',NULL,2);
INSERT OR IGNORE INTO lk_tier (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('full','Full','كامل','OPTIMIZED',NULL,3);

-- lk_platform
CREATE TABLE IF NOT EXISTS lk_platform (
    code TEXT PRIMARY KEY, name_en TEXT, name_ar TEXT,
    usacm_map TEXT, map_note TEXT, sort_order INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('all','All Platforms','كل المنصات',NULL,'surface via artifact_tags Technology',0);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('windows','Windows','ويندوز',NULL,NULL,1);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('macos','macOS','ماك',NULL,NULL,2);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('linux','Linux','لينكس',NULL,NULL,3);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('ios','iOS','iOS',NULL,NULL,4);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('android','Android','أندرويد',NULL,NULL,5);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('web','Web','ويب',NULL,NULL,6);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('browser','Browser','المتصفح',NULL,NULL,7);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('router','Router','راوتر',NULL,NULL,8);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('iot','IoT','إنترنت الأشياء',NULL,NULL,9);
INSERT OR IGNORE INTO lk_platform (code,name_en,name_ar,usacm_map,map_note,sort_order) VALUES ('cloud','Cloud','سحابة',NULL,NULL,10);

-- scoring_policy + scoring_bands (tables created in 007)
INSERT OR IGNORE INTO scoring_policy (id,critical_cap,dependency_clamp_ceiling,accepted_risk_lifts_cap,note) VALUES ('default',60,0.5,0,'amani-equivalent: critical cap 60, dependency clamp 0.5');
INSERT OR IGNORE INTO scoring_bands (policy_id,band_code,min_score,label_en,label_ar,sort_order) VALUES ('default','at_risk',0,'At Risk','في خطر',0);
INSERT OR IGNORE INTO scoring_bands (policy_id,band_code,min_score,label_en,label_ar,sort_order) VALUES ('default','fair',61,'Fair','مقبول',1);
INSERT OR IGNORE INTO scoring_bands (policy_id,band_code,min_score,label_en,label_ar,sort_order) VALUES ('default','strong',75,'Strong','قوي',2);
INSERT OR IGNORE INTO scoring_bands (policy_id,band_code,min_score,label_en,label_ar,sort_order) VALUES ('default','excellent',90,'Excellent','ممتاز',3);

-- amani_domain_alias (table created in 007)
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('identity_accounts','SD-03','SD-03.02',0.75,1,'accounts/passwords; spans lifecycle+authz');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('devices','SD-04','SD-04.02',0.8,0,'endpoint security');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('applications_browsing','SD-05',NULL,0.6,1,'apps(SD-05) vs browsing/web(SD-04.05)');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('communications','SD-04','SD-04.05',0.75,0,'email/web/digital comms');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('networks_connectivity','SD-04','SD-04.01',0.85,0,'network & comms security');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('financial_transactions','SD-02',NULL,0.5,1,'personal concept; not a clean SDT domain');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('data_privacy','SD-02','SD-02.04',0.7,1,'data protection / privacy');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('physical_travel','SD-08','SD-08.04',0.75,0,'physical & environmental');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('human_factors','SD-08','SD-08.01',0.8,0,'awareness & training');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('incident_recovery','SD-07','SD-07.01',0.8,0,'incident management');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('smart_home_iot','SD-04','SD-04.02',0.6,1,'IoT/endpoint');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('GRC','SD-01',NULL,0.7,1,'Governance, Risk & Compliance');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('IAM','SD-03','SD-03.03',0.8,0,'Identity & Access Management');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('IPS','SD-04',NULL,0.6,1,'Infrastructure Protection & Security');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('DPP','SD-02','SD-02.04',0.75,0,'Data Protection & Privacy');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('DMR','SD-06',NULL,0.6,1,'Detection, Monitoring & Response');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('APP','SD-05','SD-05.01',0.8,0,'Application Security');
INSERT OR IGNORE INTO amani_domain_alias (amani_key,sdt_primary,sdt_sub,confidence,needs_review,note) VALUES ('RCR','SD-07','SD-07.04',0.75,0,'Resilience, Continuity & Recovery');
