-- ============================================================================
-- SecureGuide — Migration 011: Universal Fallback Values (SADP v1.0 §2.3)
-- ----------------------------------------------------------------------------
-- Generated by scripts/build_fallbacks.py. Adds *-NA / *-UNKNOWN / *-MULTI to
-- every artifact-level classification list so no classification is ever NULL.
-- Additive & idempotent (INSERT OR IGNORE). See docs/SADP_CONFORMANCE.md §4.
-- ============================================================================

INSERT OR IGNORE INTO schema_migrations (version, description)
VALUES ('011', 'Universal fallback values *-NA/*-UNKNOWN/*-MULTI across classification lists (SADP 2.3)');

-- lk_control_nature
INSERT OR IGNORE INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_control_nature (code, name_en, name_ar, sort_order) VALUES ('NAT-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_control_function
INSERT OR IGNORE INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_control_function (code, name_en, name_ar, sort_order) VALUES ('FUN-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_testability
INSERT OR IGNORE INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 90);
INSERT OR IGNORE INTO lk_testability (code, name_en, name_ar, sort_order) VALUES ('TST-MULTI', 'Multiple Values', 'قيم متعددة', 91);

-- lk_requirement_type
INSERT OR IGNORE INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_requirement_type (code, name_en, name_ar, sort_order) VALUES ('RQT-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_priority
INSERT OR IGNORE INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_priority (code, name_en, name_ar, sort_order) VALUES ('PRI-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_obligation_source
INSERT OR IGNORE INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_obligation_source (code, name_en, name_ar, sort_order) VALUES ('SRC-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_obligation_level
INSERT OR IGNORE INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_obligation_level (code, name_en, name_ar, sort_order) VALUES ('OBL-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_abstraction_level
INSERT OR IGNORE INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_abstraction_level (code, name_en, name_ar, sort_order) VALUES ('ABS-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_granularity_level
INSERT OR IGNORE INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_granularity_level (code, name_en, name_ar, sort_order) VALUES ('GRN-MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_effectiveness
INSERT OR IGNORE INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_effectiveness (code, name_en, name_ar, sort_order) VALUES ('EFF-MULTI', 'Multiple Values', 'قيم متعددة', 91);

-- lk_exception_status
INSERT OR IGNORE INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 90);
INSERT OR IGNORE INTO lk_exception_status (code, name_en, name_ar, sort_order) VALUES ('EXC-MULTI', 'Multiple Values', 'قيم متعددة', 91);

-- lk_review_frequency
INSERT OR IGNORE INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_review_frequency (code, name_en, name_ar, sort_order) VALUES ('MULTI', 'Multiple Values', 'قيم متعددة', 92);

-- lk_mapping_strength
INSERT OR IGNORE INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('NA', 'Not Applicable', 'لا ينطبق', 90);
INSERT OR IGNORE INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 91);
INSERT OR IGNORE INTO lk_mapping_strength (code, name_en, name_ar, sort_order) VALUES ('MULTI', 'Multiple Values', 'قيم متعددة', 92);
