-- ============================================================================
-- SecureGuide — Migration 013: Threat reference data (SADP v1.0 §2.4/§2.6)
-- ----------------------------------------------------------------------------
-- Generated by scripts/build_threat_reference.py. Seeds the canonical THR-*
-- taxonomy + fallbacks into lk_threat, and the reviewable amani_threat_alias.
-- Additive & idempotent. Recorded in docs/SADP_CONFORMANCE.md §5.
-- ============================================================================

INSERT OR IGNORE INTO schema_migrations (version, description)
VALUES ('013', 'Canonical THR-* threat taxonomy + amani_threat_alias (SADP 2.4)');

-- ---- lk_threat : canonical taxonomy ----
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-MALWARE', 'Malware', 'برمجيات خبيثة', 'malicious_code', 0);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-RANSOMWARE', 'Ransomware & Extortion', 'فدية وابتزاز', 'malicious_code', 1);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-PHISHING', 'Phishing', 'تصيّد', 'social', 2);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-SOCIAL-ENGINEERING', 'Social Engineering', 'هندسة اجتماعية', 'social', 3);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-CREDENTIAL-THEFT', 'Credential Theft', 'سرقة بيانات الاعتماد', 'identity', 4);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-ACCOUNT-TAKEOVER', 'Account Takeover', 'الاستيلاء على الحساب', 'identity', 5);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-DATA-BREACH', 'Data Breach & Exposure', 'اختراق/كشف البيانات', 'data', 6);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-DATA-EXFILTRATION', 'Data Exfiltration', 'تسريب البيانات', 'data', 7);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-DATA-LOSS', 'Data Loss & Misdelivery', 'فقد/سوء تسليم البيانات', 'data', 8);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-UNAUTHORIZED-ACCESS', 'Unauthorized Access & Intrusion', 'وصول غير مصرّح/اختراق', 'access', 9);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-NETWORK-ATTACK', 'Network & Web Attack', 'هجوم شبكي/ويب', 'network', 10);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-INTERCEPTION', 'Interception & Eavesdropping', 'اعتراض/تنصّت', 'network', 11);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-DEVICE-COMPROMISE', 'Device & System Compromise', 'اختراق الجهاز/النظام', 'endpoint', 12);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-DEVICE-LOSS', 'Device Loss or Theft', 'فقد/سرقة الجهاز', 'physical', 13);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-PHYSICAL', 'Physical & Tampering', 'مادي/عبث', 'physical', 14);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-SURVEILLANCE', 'Surveillance & Tracking', 'مراقبة/تتبّع', 'privacy', 15);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-VULNERABILITY-EXPLOIT', 'Vulnerability Exploitation', 'استغلال الثغرات', 'exploitation', 16);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-FINANCIAL-FRAUD', 'Financial Fraud', 'احتيال مالي', 'fraud', 17);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-TARGETED-ATTACK', 'Targeted Attack', 'هجوم موجّه', 'exploitation', 18);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-MISCONFIG', 'Misconfiguration & Drift', 'سوء إعداد/انحراف', 'configuration', 19);
-- fallbacks (SADP §2.3)
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-NA', 'Not Applicable', 'لا ينطبق', 'fallback', 90);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-UNKNOWN', 'Unknown / Undecided', 'غير محسوم', 'fallback', 91);
INSERT OR IGNORE INTO lk_threat (code, name_en, name_ar, category, sort_order) VALUES ('THR-MULTI', 'Multiple Threats', 'تهديدات متعددة', 'fallback', 92);

-- ---- amani_threat_alias : amani vocabulary -> THR-* ----
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('THR-DATA-EXFIL-001', 'THR-DATA-EXFILTRATION', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('THR-INTRUSION-001', 'THR-UNAUTHORIZED-ACCESS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('THR-MALWARE-001', 'THR-MALWARE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('THR-RANSOMWARE-001', 'THR-RANSOMWARE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('THR-WEB-ATTACK-001', 'THR-NETWORK-ATTACK', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('account_lockout', 'THR-ACCOUNT-TAKEOVER', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('account_takeover', 'THR-ACCOUNT-TAKEOVER', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('border_search', 'THR-PHYSICAL', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('cloud_compromise', 'THR-UNAUTHORIZED-ACCESS', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('credential_attack', 'THR-CREDENTIAL-THEFT', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('credential_theft', 'THR-CREDENTIAL-THEFT', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('data_breach', 'THR-DATA-BREACH', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('data_exfiltration', 'THR-DATA-EXFILTRATION', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('data_exposure', 'THR-DATA-BREACH', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('data_loss', 'THR-DATA-LOSS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('data_retention', 'THR-DATA-LOSS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('device_compromise', 'THR-DEVICE-COMPROMISE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('device_loss_theft', 'THR-DEVICE-LOSS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('exposure_targeting', 'THR-SURVEILLANCE', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('extortion', 'THR-RANSOMWARE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('financial_fraud', 'THR-FINANCIAL-FRAUD', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('identity_theft', 'THR-ACCOUNT-TAKEOVER', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('iot_compromise', 'THR-DEVICE-COMPROMISE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('lateral_movement', 'THR-VULNERABILITY-EXPLOIT', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('limited_control', 'THR-MISCONFIG', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('malicious_charging', 'THR-DEVICE-COMPROMISE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('malware', 'THR-MALWARE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('message_interception', 'THR-INTERCEPTION', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('misdelivery', 'THR-DATA-LOSS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('network_compromise', 'THR-NETWORK-ATTACK', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('network_interception', 'THR-INTERCEPTION', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('phishing', 'THR-PHISHING', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('physical_risk', 'THR-PHYSICAL', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('proximity_attack', 'THR-INTERCEPTION', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('ransomware', 'THR-RANSOMWARE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('router_compromise', 'THR-NETWORK-ATTACK', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('security_drift', 'THR-MISCONFIG', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('session_hijacking', 'THR-ACCOUNT-TAKEOVER', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('shoulder_surfing', 'THR-SURVEILLANCE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('sim_swap', 'THR-ACCOUNT-TAKEOVER', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('single_point_failure', 'THR-MISCONFIG', 1);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('social_engineering', 'THR-SOCIAL-ENGINEERING', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('surveillance', 'THR-SURVEILLANCE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('tampering', 'THR-PHYSICAL', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('targeted_attack', 'THR-TARGETED-ATTACK', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('third_party_access_abuse', 'THR-UNAUTHORIZED-ACCESS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('tracking_profiling', 'THR-SURVEILLANCE', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('unauthorized_access', 'THR-UNAUTHORIZED-ACCESS', 0);
INSERT OR IGNORE INTO amani_threat_alias (amani_key, threat_code, needs_review) VALUES ('vulnerability_exploitation', 'THR-VULNERABILITY-EXPLOIT', 0);
