# -*- coding: utf-8 -*-
"""Generate migrations/011_universal_fallbacks.sql — SADP v1.0 §2.3.

Seeds the mandatory fallback triple (*-NA / *-UNKNOWN / *-MULTI) into every
artifact-level classification list, respecting each list's code prefix and
reusing any equivalent that already exists (e.g. TST-NA, EFF-UNKNOWN). The
threat list (lk_threat) gets its fallbacks in migration 013 alongside the
canonical THR-* values. Domain / sub-domain / artifact_type are intentionally
excluded — those must always carry a real value (the promotion gate rejects a
fallback there). Every value added here is recorded in docs/SADP_CONFORMANCE.md
(§2.6 change control)."""
import io
import os

MIG = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'migrations'))
OUT = os.path.join(MIG, '011_universal_fallbacks.sql')

SUFFIX = {
    'NA': ('Not Applicable', 'لا ينطبق'),
    'UNKNOWN': ('Unknown / Undecided', 'غير محسوم'),
    'MULTI': ('Multiple Values', 'قيم متعددة'),
}

# list -> (prefix or '' for unprefixed, [suffixes to add])
# existing equivalents are omitted from the suffix list so INSERT OR IGNORE
# stays a no-op for them and the intent is explicit.
TARGETS = [
    ('lk_control_nature', 'NAT-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_control_function', 'FUN-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_testability', 'TST-', ['UNKNOWN', 'MULTI']),              # TST-NA exists
    ('lk_requirement_type', 'RQT-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_priority', 'PRI-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_obligation_source', 'SRC-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_obligation_level', 'OBL-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_abstraction_level', 'ABS-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_granularity_level', 'GRN-', ['NA', 'UNKNOWN', 'MULTI']),
    ('lk_effectiveness', 'EFF-', ['NA', 'MULTI']),                 # EFF-UNKNOWN exists
    ('lk_exception_status', 'EXC-', ['UNKNOWN', 'MULTI']),         # EXC-NOT-APPLICABLE / EXC-NONE exist
    ('lk_review_frequency', '', ['NA', 'UNKNOWN', 'MULTI']),       # unprefixed
    ('lk_mapping_strength', '', ['NA', 'UNKNOWN', 'MULTI']),       # unprefixed
]

BASE_SORT = 90  # push fallbacks to the end of each list


def q(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    lines = [
        '-- ============================================================================',
        '-- SecureGuide — Migration 011: Universal Fallback Values (SADP v1.0 §2.3)',
        '-- ----------------------------------------------------------------------------',
        '-- Generated by scripts/build_fallbacks.py. Adds *-NA / *-UNKNOWN / *-MULTI to',
        '-- every artifact-level classification list so no classification is ever NULL.',
        '-- Additive & idempotent (INSERT OR IGNORE). See docs/SADP_CONFORMANCE.md §4.',
        '-- ============================================================================',
        '',
        "INSERT OR IGNORE INTO schema_migrations (version, description)",
        "VALUES ('011', 'Universal fallback values *-NA/*-UNKNOWN/*-MULTI across classification lists (SADP 2.3)');",
        '',
    ]
    for table, prefix, suffixes in TARGETS:
        lines.append(f'-- {table}')
        for i, suf in enumerate(suffixes):
            code = prefix + suf
            en, ar = SUFFIX[suf]
            lines.append(
                f"INSERT OR IGNORE INTO {table} (code, name_en, name_ar, sort_order) "
                f"VALUES ({q(code)}, {q(en)}, {q(ar)}, {BASE_SORT + i});")
        lines.append('')
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    n = sum(len(s) for _, _, s in TARGETS)
    print(f"wrote {OUT} ({n} fallback values across {len(TARGETS)} lists)")


if __name__ == '__main__':
    main()
